#!/bin/sh

if
    test "$X_DPI" -gt 96;
then
    bspc config top_padding 16;
    bspc config right_padding 12;
    bspc config bottom_padding 16;
    bspc config left_padding 12;
    bspc config border_width 8;
    bspc config window_gap 4;
else
    bspc config top_padding 8;
    bspc config right_padding 6;
    bspc config bottom_padding 8;
    bspc config left_padding 6;
    bspc config border_width 4;
    bspc config window_gap 2;
fi;

bspc config active_border_color \#555555;
bspc config focused_border_color \#555555;
bspc config presel_feedback_color \#555555;

if
    test -f "$XDG_RUNTIME_DIR/"DAYLIGHT;
then
    bspc config normal_border_color \#E0E0E0;
else
    bspc config normal_border_color \#222222;
fi;

bspc config split_ratio 0.50;
#status_prefix;
bspc config external_rules_command "$XDG_BIN_HOME/"bspwm-rules;
bspc config initial_polarity second_child;
bspc config borderless_monocle true;
bspc config gapless_monocle true;
bspc config paddingless_monocle true;
bspc config single_monocle true;
#pointer_motion_interval;
bspc config pointer_modifier mod4;
bspc config pointer_action1 move;
bspc config pointer_action2 resize_side;
bspc config pointer_action3 resize_corner;
bspc config click_to_focus true;
bspc config focus_follows_pointer false;
bspc config pointer_follows_focus true;
bspc config pointer_follows_monitor true;
bspc config ignore_ewmh_focus true;
bspc config center_pseudo_tiled true;
bspc config honor_size_hints false;
bspc config remove_disabled_monitors true;
bspc config remove_unplugged_monitors true;
bspc config merge_overlapping_monitors true;

bspc monitor --reset-desktops nogroup one two three four end;

bspc wm --record-history on;

# vim: set ft=sh :
